### ISSUE TITLE
Problem with migrations while starting new server (docker)

### ISSUE THREAD

**Issue by mlunax** [ellie/atuin#1031]
Docker logs:
```
atuin-postgresql-1  | 2023-06-06T09:21:03.249712055Z 2023-06-06 09:21:03.249 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
atuin-postgresql-1  | 2023-06-06T09:21:03.249879278Z 2023-06-06 09:21:03.249 UTC [1] LOG:  listening on IPv6 address "::", port 5432
atuin-postgresql-1  | 2023-06-06T09:21:03.253858313Z 2023-06-06 09:21:03.253 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
atuin-postgresql-1  | 2023-06-06T09:21:03.258330635Z 2023-06-06 09:21:03.258 UTC [62] LOG:  database system was shut down at 2023-06-06 09:21:03 UTC
atuin-postgresql-1  | 2023-06-06T09:21:03.262170509Z 2023-06-06 09:21:03.262 UTC [1] LOG:  database system is ready to accept connections
atuin-atuin-1       | 2023-06-06T09:22:09.203446676Z Error: failed to connect to db: postgres://atuin:password@db/atuin
atuin-atuin-1       | 2023-06-06T09:22:09.203481701Z
atuin-atuin-1       | 2023-06-06T09:22:09.203484286Z Caused by:
atuin-atuin-1       | 2023-06-06T09:22:09.203486321Z    0: while executing migrations: error returned from database: syntax error at or near "trigger"
atuin-atuin-1       | 2023-06-06T09:22:09.203488475Z    1: while executing migrations: error returned from database: syntax error at or near "trigger"
atuin-atuin-1       | 2023-06-06T09:22:09.203490459Z    2: error returned from database: syntax error at or near "trigger"
atuin-atuin-1       | 2023-06-06T09:22:09.203804568Z    3: syntax error at or near "trigger"
```
My compose:
```
version: '3'
services:
  atuin:
    restart: always
    image: ghcr.io/ellie/atuin:main
    command: server start
     volumes:
      - "./config:/config"
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@db/atuin
  postgresql:
    image: postgres:14
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: $ATUIN_DB_USERNAME
      POSTGRES_PASSWORD: $ATUIN_DB_PASSWORD
      POSTGRES_DB: atuin
```
