### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by miki725** [ellie/atuin#57]
Will be great if fish shell can be supported as well

**Comment by bl-ue** [comment]
I'd be willing to give this a try.

[ ] Plugin
[ ] Importing history
[ ] Importing complex history (if fish supports that)

**Comment by conradludgate** [comment]
@bl-ue #71 is in now :)

**Comment by bl-ue** [comment]
Wow, thanks a lot @pitr — I'm still relatively new to fish and haven't done a lot of this type of stuff with it, so that was giving me some trouble.  Fish uses YAML for its history format, so I'll be opening a PR with the importer soon!

@pitr do you mind if I include that fish shell snippet in my PR?

**Comment by bl-ue** [comment]
(sorry, I'm not totally sure:) So it's okay with you if I use your code?

**Comment by pitr** [comment]
probably shouldn't be default for everyone, but an idea to consider - store cancelled commands in history also (ie enter command in the prompt but instead of Enter, press Ctrl-c):

```fish
function _atui_cancel
    set -l cmd (commandline)
    commandline -f cancel-commandline
    if test -n "$cmd"
        RUST_LOG=error atuin history end (atuin history start "$cmd") --exit 42 &; disown
    end
end

bind \cc '_atui_cancel'
```

**Comment by matthewess** [comment]
@bl-ue looking forward to a PR for this!

**Comment by bl-ue** [comment]
I'll try to get a PR open within a few days — I've done some Rust development, but not enough to make me an expert like I am in other langs 😄

The fish history is a little different from the other shells' history, because a single command takes multiple lines (since it's YAML).  For example:
```yaml
- cmd: node
  when: 1618340414
- cmd: yes | wc -l &; sleep 1000; ps -ax | grep yes | grep -v grep | awk '{print $1}' | xargs kill; open .
  when: 1618340743
  paths:
    - .
- cmd: date
  when: 1618340762
- cmd: echo hello; exit
  when: 1618340779
- cmd: cd ~/Code; cd ~/Code/rust;
  when: 1618341861
  paths:
    - ~/Code
    - ~/Code/rust
```
And I'm a little unsure how to, in `next()` of `impl<R: Read> Iterator for Fish<R>`, check if the history entry is fully read.  I was thinking to check if the line begins with `- cmd` and then `self.file.seek(-1)`, if that's even possible... @conradludgate does that sound like a feasible solution?
